services:
  docs:
    image: vm_local_docs
    container_name: vm_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./vm:/app/vm:z
    ports:
      - '9000:9000'
    command: /start-docs
