apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: celerybeat
  namespace: production
  name: celerybeat
spec:
  replicas: 1
  selector:
    matchLabels:
      service: celerybeat
  template:
    metadata:
      labels:
        service: celerybeat
    spec:
      containers:
        - args:
            - /start-celerybeat
          envFrom:
            - configMapRef:
                name: envs-production-django
            - configMapRef:
                name: envs-production-postgres
            - secretRef:
                name: secrets-production-django
            - secretRef:
                name: secrets-production-postgres
          image: <CR_URL>/autovm_production_celerybeat
          name: celerybeat
          resources: {}
          volumeMounts:
            - mountPath: /app/autovm/media
              name: media-local-storage
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: media-local-storage
          persistentVolumeClaim:
            claimName: media-local-storage
