apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: production
  name: media-local-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
  /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: media-local-storage
spec:
  accessModes:
    - ReadWriteMany
  volumeName: media-local-storage
  resources:
    requests:
      storage: 5Gi
