apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default # Use default storage class
  resources:
    requests:
      storage: 1Gi
status: {}
